### ISSUE TITLE
Someone has charged me for your hosted link bro

### ISSUE THREAD

**Issue by Ghost666666666666** [rafasantos/twilio-sms-web#5]
hello bro someone has charged me a lot of money for your hosted link, please take down your hosted link, only supply source code this will prevent from others selling this. this is all wrong why have i been charged money when you hosted link here free??????????????? please take down i am not able to bare this trauma.

**Comment by rafacandev** [comment]
Hi @Ghost666666666666 ,

That's terrible. Do you feel comfortable in sharing more details? Specially, if folks charging you were a company or individual? Hopefully we can think in a way to prevent such thing to happen again.

I'm thinking about your suggestion but I'm *not sure* if that's going to work because with minimal programming logic, anybody can fork this project and re-host on github in less than 5min. Including multiple versions of this software. So, I am afraid that as soon as the github page is removed; another website is  going to come back up.

Finally, for clarification. This app is open source and free under then MIT License. However, this app is merely a user interface for the [Twilio SMS API](https://www.twilio.com/docs/sms/api) and users need to comply with Twilio's terms and services including legal responsibilities and paying fees for telephone purchases and messages sent/received. See https://www.twilio.com/sms/pricing/ca
