### ISSUE TITLE
send/recive media

### ISSUE THREAD

**Issue by vsbehter** [rafasantos/twilio-sms-web#7]
it wont show received media files (like photos), and can you add ability to send media files as well

**Comment by rafacandev** [comment]
That's an interesting request, I am going to take a look on what can be done. Out of curiosity, what has the higher priority for you: receiving or sending media files (MMS)?

I am going to take a look at receiving MMS first because I believe that can be done quicker. Also, keep in mind that it might be necessary to configure your twilio account correctly in order to be able to receive/send MMS.

Additionally, there is a number of media files that can be sent/received via MMS. I am going to start with image files (`.jpg`, `.gif`, etc) and later we can take a look at other formats like PDF.

**Comment by vsbehter** [comment]
Receiving in priority. Also could be a good idea to make notification of received message from any number, while webpage is active

**Comment by rafacandev** [comment]
@vsbehter 
> Receiving in priority.

Sounds good. I should be able to implement the receiving MMS over the new year's holiday.

> Also could be a good idea to make notification of received message from any number, while webpage is active

I am not sure if there is a way to do that without hosting a separate backend for this application. But I will take a look to see if Twilio offers anything like that.

At the moment, I wish to keep this application running without a backend.

**Comment by rafacandev** [comment]
@vsbehter 
We can now view MMS images. Checkout the [release notes](https://github.com/rafacandev/twilio-sms-web/releases/tag/v1.1.0) for more details. Let me know if you have questions/concerns. Thank you.
